<a href="https://colab.research.google.com/github/ibrahimfe/Machine_Learning_Project/blob/main/Machine_Learning_Project_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# A Model That Can Classifies Image Input from MNIST

## Load The MNIST Dataset in Keras

In [1]:
from keras.datasets import mnist
(train_images, train_labels) , (test_images, test_labels) = mnist.load_data()

2023-06-08 08:05:33.085081: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


11490434/11490434 [==============================] - 42s 4us/step


In [2]:
train_images.shape

(60000, 28, 28)

In [3]:
len(train_labels)

60000

In [4]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [5]:
test_images.shape

(10000, 28, 28)

In [6]:
len(test_labels)

10000

In [7]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

## The Neural Network Architecture

In [8]:
from tensorflow import keras
from keras import layers
from keras.losses import sparse_categorical_crossentropy
model = keras.Sequential([
    layers.Dense(512, activation="relu"),
    layers.Dense(10, activation="softmax")
])

## Compilation

In [9]:
model.compile(optimizer="rmsprop", loss="sparse_categorical_crossentropy", metrics=["accuracy"])

## Prepare The Image Data

In [10]:
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype("float32") / 255
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype("float32")/ 255

## Fitting The Model

In [11]:
model.fit(train_images, train_labels, epochs=5, batch_size=128)

2023-06-08 08:06:51.987250: W tensorflow/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 188160000 exceeds 10% of free system memory.


Epoch 1/5
469/469 [==============================] - 16s 28ms/step - loss: 0.2633 - accuracy: 0.9240
Epoch 2/5
469/469 [==============================] - 13s 28ms/step - loss: 0.1073 - accuracy: 0.9687
Epoch 3/5
469/469 [==============================] - 16s 35ms/step - loss: 0.0709 - accuracy: 0.9790
Epoch 4/5
469/469 [==============================] - 24s 52ms/step - loss: 0.0515 - accuracy: 0.9846
Epoch 5/5
469/469 [==============================] - 23s 48ms/step - loss: 0.0388 - accuracy: 0.9884


## Using The Model To make Predictions

In [12]:
test_digits = test_images[0:10]
predictions = model.predict(test_digits)
predictions[0]

1/1 [==============================] - 3s 3s/step


array([1.66582055e-08, 7.66608821e-09, 4.17012143e-06, 3.85470012e-05,
       4.93965591e-10, 1.35247561e-07, 8.30053474e-13, 9.99949634e-01,
       1.10055765e-07, 7.40084715e-06], dtype=float32)

In [13]:
predictions[0].argmax()
predictions[0][7]

0.99994963

In [14]:
test_labels[0]

7

## Evaluating The Model on New Data

In [15]:
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(f"test accepted : {test_acc}")

2023-06-08 08:09:35.841877: W tensorflow/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 31360000 exceeds 10% of free system memory.


313/313 [==============================] - 6s 14ms/step - loss: 0.0628 - accuracy: 0.9802
test accepted : 0.9801999926567078
