<a href="https://colab.research.google.com/github/ibrahimfe/Machine_Learning_Project/blob/main/Machine_Learning_Project_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# A Model That Can Classifies Image Input from MNIST

## Load The MNIST Dataset in Keras

In [38]:
from keras.datasets import mnist
(train_images, train_labels) , (test_images, test_labels) = mnist.load_data()

In [39]:
train_images.shape

(60000, 28, 28)

In [40]:
len(train_labels)

60000

In [41]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [42]:
test_images.shape

(10000, 28, 28)

In [43]:
len(test_labels)

10000

In [44]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

## The Neural Network Architecture

In [45]:
from tensorflow import keras
from keras import layers
from keras.losses import sparse_categorical_crossentropy
model = keras.Sequential([
    layers.Dense(512, activation="relu"),
    layers.Dense(10, activation="softmax")
])

## Compilation

In [46]:
model.compile(optimizer="rmsprop", loss="sparse_categorical_crossentropy", metrics=["accuracy"])

## Prepare The Image Data

In [47]:
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype("float32") / 255
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype("float32")/ 255

## Fitting The Model

In [49]:
model.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
469/469 [==============================] - 4s 8ms/step - loss: 0.2610 - accuracy: 0.9248
Epoch 2/5
469/469 [==============================] - 5s 10ms/step - loss: 0.1069 - accuracy: 0.9687
Epoch 3/5
469/469 [==============================] - 4s 8ms/step - loss: 0.0697 - accuracy: 0.9792
Epoch 4/5
469/469 [==============================] - 4s 8ms/step - loss: 0.0511 - accuracy: 0.9848
Epoch 5/5
469/469 [==============================] - 6s 12ms/step - loss: 0.0381 - accuracy: 0.9884


## Using The Model To make Predictions

In [50]:
test_digits = test_images[0:10]
predictions = model.predict(test_digits)
predictions[0]

1/1 [==============================] - 0s 77ms/step


array([2.1018700e-08, 1.0706095e-09, 2.3868968e-06, 3.2397420e-05,
       2.5622379e-11, 1.6897538e-08, 5.1780693e-13, 9.9996489e-01,
       3.6345050e-08, 2.0667579e-07], dtype=float32)

In [52]:
predictions[0].argmax()
predictions[0][7]

0.9999649

In [53]:
test_labels[0]

7

## Evaluating The Model on New Data

In [54]:
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(f"test accepted : {test_acc}")

313/313 [==============================] - 1s 3ms/step - loss: 0.0740 - accuracy: 0.9770
test accepted : 0.9769999980926514
